version: '3'

services:
  mysql-master:
    image: mysql:8
    container_name: mysql-master
    working_dir: /opt
    ports:
      - 3307:3306
    volumes:
      - ./master/cnf:/etc/mysql/conf.d
      - ./master/sql:/opt
      - mysql-master-data:/var/lib/mysql
    env_file:
      - ./mysql-cluster.env
  nginx:
    image: nginx:1.22
    container_name: nginx
    ports:
      - 3308:3306
    volumes:
      - ./nginx/conf/nginx.conf:/etc/nginx/nginx.conf
  mysql-slave-1:
    image: mysql:8
    container_name: mysql-slave-1
    working_dir: /opt
    volumes:
      - ./slave-1/cnf:/etc/mysql/conf.d
      - ./slave/sql:/opt
      - mysql-slave-1-data:/var/lib/mysql
    env_file:
      - ./mysql-cluster.env
  mysql-slave-2:
    image: mysql:8
    container_name: mysql-slave-2
    working_dir: /opt
    volumes:
      - ./slave-2/cnf:/etc/mysql/conf.d
      - ./slave/sql:/opt
      - mysql-slave-2-data:/var/lib/mysql
    env_file:
      - ./mysql-cluster.env

volumes:
  mysql-master-data:
  mysql-slave-1-data:
  mysql-slave-2-data:
