version: '3'

services:
  mysql-master:
    image: mysql:8
    container_name: mysql-master
    ports:
      - 3307:3306
    volumes:
      - ./master/cnf:/etc/mysql/conf.d
      - mysql-master-data:/var/lib/mysql
    env_file:
      - ./mysql-cluster.env
    environment:
      - MYSQL_USER=reader
      - MYSQL_PASSWORD=reader
  nginx:
    image: nginx
    container_name: nginx:1.22
    ports:
      - 3308:3306
    volumes:
      - ./nginx/conf/nginx.conf:/etc/nginx/nginx.conf
  mysql-slave-1:
    image: mysql:8
    container_name: mysql-slave-1
    volumes:
      - ./slave-1/cnf:/etc/mysql/conf.d
      - mysql-slave-1-data:/var/lib/mysql
    env_file:
      - ./mysql-cluster.env
  mysql-slave-2:
    image: mysql:8
    container_name: mysql-slave-2
    volumes:
      - ./slave-2/cnf:/etc/mysql/conf.d
      - mysql-slave-2-data:/var/lib/mysql
    env_file:
      - ./mysql-cluster.env

volumes:
  mysql-master-data:
  mysql-slave-1-data:
  mysql-slave-2-data:
